### ISSUE TITLE
Hi, Installed the game, and when I drop the file into the folder, it gives me this error when I run the patcher, even in admin mode.

### ISSUE THREAD

**Issue by SuperSonic1528** [rtsonneveld/DonaldDuckPatcher#2]
Donald Duck Quack Attack / Goin' Quackers PC Patcher for Modern PC's
IOException, try running this batch file as administrator
System.IO.IOException: The process cannot access the file 'C:\Program Files\Disney Interactive\Donald Duck\Donald.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at DonaldDuckPatcher.Program.Main(String[] args)
Press any key to continue...

**Comment by SuperSonic1528** [comment]
Here is the issue. If you open the game on windows 11 WITHOUT THE PATCH, it will seem like it isn't open, but it actually is in the background. Open task manager, end the game task, and install the patch.
